### ISSUE TITLE
Please add a license file and a readme

### ISSUE THREAD

**Issue by unixorn** [sbfaulkner/chgo-plugin-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file or readme.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by sbfaulkner** [comment]
https://github.com/sbfaulkner/chgo-plugin-zsh/blob/main/LICENSE.txt
